name: 'Transmute JSON-LD to Cypher Action'
description: |
  This action enables JSON-LD to Cypher within GitHub Workflows.
inputs:
  neo4j-uri:
    description: |
      Neo4j Connection URL.
    require: true
  neo4j-user:
    description: |
      Neo4j User.
    require: true
  neo4j-password:
    description: |
      Neo4j Password.
    require: true
  operation:
    description: |
      A JSON-LD Operation.
    require: true
  document:
    description: |
      A JSON Document (string).
    require: true

outputs:
  json:
    description: 'The output as json.'

runs:
  using: 'node16'
  main: 'dist/index.js'
